### PR TITLE
feat: Transaction Enhance

### PR DESCRIPTION
**Pull request by Oskang09**
Changes
* Return `*Transaction` instead of `*SessionContext` when start a transaction
* `*Transaction.Table()` return `*Table` instead of `*Session` able to use table crud method directly.
* Reliability testing file for transactions call `all actions`

Pending
* Examples

[LAST EDIT] 07/12/2019 21:46

### CODE REVIEW

**Comment by si3nloong** [comment]
The SessionContext designed as this is because we want to control the user behaviour and prevent user make mistake on Transaction. The reason behind is transaction cannot rollback statements such as create or drop databases, those that create, drop, or alter tables or stored routines.

**Comment by Oskang09** [comment]
If so, if we have an interface for this 2 struct or some handling to prevent those statement unable to work well in transaction mode?

Expected usage.
```
client *sqlike.Client

func (trx *sqlike.Transaction) {
    query := client.Table()
        if trx != nil {
            query = trx.Table()
        }
}
```

But current unable to do so because of not the same struct. Is this a good idea for make some handling instead of new struct? by checking is it under transaction mode?

**Comment by si3nloong** [comment]
I think the way you suggested make sense, I will put some warning message when the user using unsupported ddl in transaction mode. Besides, can you update the test case value checking by using require package?

**Comment by Oskang09** [comment]
Sure, i will commit later on.

**Pull request merged**
